apiVersion: v1
kind: Service
metadata:
  name: psdte-api
  namespace: psdte
spec:
  selector:
    app.kubernetes.io/name: psdte-api
  ports:
    - name: http
      port: 3001
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: psdte-web
  namespace: psdte
spec:
  selector:
    app.kubernetes.io/name: psdte-web
  ports:
    - name: http
      port: 3000
      targetPort: http
