apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: psdte
resources:
  - ../../base
  - ../../postgres/statefulset.yaml # SOLO en dev — ver comentario en ese archivo
patches:
  - path: configmap-patch.yaml
  - path: replicas-patch.yaml
  - target:
      kind: Ingress
      name: psdte
    path: ingress-patch.yaml
images:
  - name: psdte-api
    newTag: dev
  - name: psdte-api-worker
    newTag: dev
  - name: psdte-web
    newTag: dev
